package com.letvcloud.uc.infra.mybatis.mapper;

import com.letvcloud.uc.ms.model.UcUserInfo;
import com.letvcloud.uc.mapper.annotations.MyBatisDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@MyBatisDao
public interface UcUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int countByExample(UcUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int deleteByExample(UcUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int insert(UcUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int insertSelective(UcUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    List<UcUserInfo> selectByExample(UcUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    UcUserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") UcUserInfo record, @Param("example") UcUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int updateByExample(@Param("record") UcUserInfo record, @Param("example") UcUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int updateByPrimaryKeySelective(UcUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    int updateByPrimaryKey(UcUserInfo record);
}