package com.letvcloud.uc.infra.mybatis.mapper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UcUserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    protected int[] limit = new int[] {-1, -1};

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public UcUserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setLimitValue1(int val) {
        this.limit[0] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setLimitValue2(int val) {
        this.limit[1] = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public int getLimitValue1() {
        return this.limit[0];
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public int getLimitValue2() {
        return this.limit[1];
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("parentId is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("parentId is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Long value) {
            addCriterion("parentId =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Long value) {
            addCriterion("parentId <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Long value) {
            addCriterion("parentId >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Long value) {
            addCriterion("parentId >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Long value) {
            addCriterion("parentId <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Long value) {
            addCriterion("parentId <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Long> values) {
            addCriterion("parentId in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Long> values) {
            addCriterion("parentId not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Long value1, Long value2) {
            addCriterion("parentId between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Long value1, Long value2) {
            addCriterion("parentId not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andEmailstatusIsNull() {
            addCriterion("emailStatus is null");
            return (Criteria) this;
        }

        public Criteria andEmailstatusIsNotNull() {
            addCriterion("emailStatus is not null");
            return (Criteria) this;
        }

        public Criteria andEmailstatusEqualTo(Byte value) {
            addCriterion("emailStatus =", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusNotEqualTo(Byte value) {
            addCriterion("emailStatus <>", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusGreaterThan(Byte value) {
            addCriterion("emailStatus >", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("emailStatus >=", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusLessThan(Byte value) {
            addCriterion("emailStatus <", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusLessThanOrEqualTo(Byte value) {
            addCriterion("emailStatus <=", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusIn(List<Byte> values) {
            addCriterion("emailStatus in", values, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusNotIn(List<Byte> values) {
            addCriterion("emailStatus not in", values, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusBetween(Byte value1, Byte value2) {
            addCriterion("emailStatus between", value1, value2, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("emailStatus not between", value1, value2, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusIsNull() {
            addCriterion("userStatus is null");
            return (Criteria) this;
        }

        public Criteria andUserstatusIsNotNull() {
            addCriterion("userStatus is not null");
            return (Criteria) this;
        }

        public Criteria andUserstatusEqualTo(Byte value) {
            addCriterion("userStatus =", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusNotEqualTo(Byte value) {
            addCriterion("userStatus <>", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusGreaterThan(Byte value) {
            addCriterion("userStatus >", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("userStatus >=", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusLessThan(Byte value) {
            addCriterion("userStatus <", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusLessThanOrEqualTo(Byte value) {
            addCriterion("userStatus <=", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusIn(List<Byte> values) {
            addCriterion("userStatus in", values, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusNotIn(List<Byte> values) {
            addCriterion("userStatus not in", values, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusBetween(Byte value1, Byte value2) {
            addCriterion("userStatus between", value1, value2, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("userStatus not between", value1, value2, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUseruniqueIsNull() {
            addCriterion("userUnique is null");
            return (Criteria) this;
        }

        public Criteria andUseruniqueIsNotNull() {
            addCriterion("userUnique is not null");
            return (Criteria) this;
        }

        public Criteria andUseruniqueEqualTo(String value) {
            addCriterion("userUnique =", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueNotEqualTo(String value) {
            addCriterion("userUnique <>", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueGreaterThan(String value) {
            addCriterion("userUnique >", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueGreaterThanOrEqualTo(String value) {
            addCriterion("userUnique >=", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueLessThan(String value) {
            addCriterion("userUnique <", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueLessThanOrEqualTo(String value) {
            addCriterion("userUnique <=", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueLike(String value) {
            addCriterion("userUnique like", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueNotLike(String value) {
            addCriterion("userUnique not like", value, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueIn(List<String> values) {
            addCriterion("userUnique in", values, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueNotIn(List<String> values) {
            addCriterion("userUnique not in", values, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueBetween(String value1, String value2) {
            addCriterion("userUnique between", value1, value2, "userunique");
            return (Criteria) this;
        }

        public Criteria andUseruniqueNotBetween(String value1, String value2) {
            addCriterion("userUnique not between", value1, value2, "userunique");
            return (Criteria) this;
        }

        public Criteria andExaminestatusIsNull() {
            addCriterion("examineStatus is null");
            return (Criteria) this;
        }

        public Criteria andExaminestatusIsNotNull() {
            addCriterion("examineStatus is not null");
            return (Criteria) this;
        }

        public Criteria andExaminestatusEqualTo(Byte value) {
            addCriterion("examineStatus =", value, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusNotEqualTo(Byte value) {
            addCriterion("examineStatus <>", value, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusGreaterThan(Byte value) {
            addCriterion("examineStatus >", value, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("examineStatus >=", value, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusLessThan(Byte value) {
            addCriterion("examineStatus <", value, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusLessThanOrEqualTo(Byte value) {
            addCriterion("examineStatus <=", value, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusIn(List<Byte> values) {
            addCriterion("examineStatus in", values, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusNotIn(List<Byte> values) {
            addCriterion("examineStatus not in", values, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusBetween(Byte value1, Byte value2) {
            addCriterion("examineStatus between", value1, value2, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andExaminestatusNotBetween(Byte value1, Byte value2) {
            addCriterion("examineStatus not between", value1, value2, "examinestatus");
            return (Criteria) this;
        }

        public Criteria andUseravatarIsNull() {
            addCriterion("userAvatar is null");
            return (Criteria) this;
        }

        public Criteria andUseravatarIsNotNull() {
            addCriterion("userAvatar is not null");
            return (Criteria) this;
        }

        public Criteria andUseravatarEqualTo(String value) {
            addCriterion("userAvatar =", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarNotEqualTo(String value) {
            addCriterion("userAvatar <>", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarGreaterThan(String value) {
            addCriterion("userAvatar >", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarGreaterThanOrEqualTo(String value) {
            addCriterion("userAvatar >=", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarLessThan(String value) {
            addCriterion("userAvatar <", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarLessThanOrEqualTo(String value) {
            addCriterion("userAvatar <=", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarLike(String value) {
            addCriterion("userAvatar like", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarNotLike(String value) {
            addCriterion("userAvatar not like", value, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarIn(List<String> values) {
            addCriterion("userAvatar in", values, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarNotIn(List<String> values) {
            addCriterion("userAvatar not in", values, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarBetween(String value1, String value2) {
            addCriterion("userAvatar between", value1, value2, "useravatar");
            return (Criteria) this;
        }

        public Criteria andUseravatarNotBetween(String value1, String value2) {
            addCriterion("userAvatar not between", value1, value2, "useravatar");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNull() {
            addCriterion("idCard is null");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNotNull() {
            addCriterion("idCard is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardEqualTo(String value) {
            addCriterion("idCard =", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotEqualTo(String value) {
            addCriterion("idCard <>", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThan(String value) {
            addCriterion("idCard >", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("idCard >=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThan(String value) {
            addCriterion("idCard <", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThanOrEqualTo(String value) {
            addCriterion("idCard <=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLike(String value) {
            addCriterion("idCard like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotLike(String value) {
            addCriterion("idCard not like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardIn(List<String> values) {
            addCriterion("idCard in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotIn(List<String> values) {
            addCriterion("idCard not in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardBetween(String value1, String value2) {
            addCriterion("idCard between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotBetween(String value1, String value2) {
            addCriterion("idCard not between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoIsNull() {
            addCriterion("idCardPhoto is null");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoIsNotNull() {
            addCriterion("idCardPhoto is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoEqualTo(String value) {
            addCriterion("idCardPhoto =", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoNotEqualTo(String value) {
            addCriterion("idCardPhoto <>", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoGreaterThan(String value) {
            addCriterion("idCardPhoto >", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoGreaterThanOrEqualTo(String value) {
            addCriterion("idCardPhoto >=", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoLessThan(String value) {
            addCriterion("idCardPhoto <", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoLessThanOrEqualTo(String value) {
            addCriterion("idCardPhoto <=", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoLike(String value) {
            addCriterion("idCardPhoto like", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoNotLike(String value) {
            addCriterion("idCardPhoto not like", value, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoIn(List<String> values) {
            addCriterion("idCardPhoto in", values, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoNotIn(List<String> values) {
            addCriterion("idCardPhoto not in", values, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoBetween(String value1, String value2) {
            addCriterion("idCardPhoto between", value1, value2, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andIdcardphotoNotBetween(String value1, String value2) {
            addCriterion("idCardPhoto not between", value1, value2, "idcardphoto");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andUserkeyIsNull() {
            addCriterion("userKey is null");
            return (Criteria) this;
        }

        public Criteria andUserkeyIsNotNull() {
            addCriterion("userKey is not null");
            return (Criteria) this;
        }

        public Criteria andUserkeyEqualTo(String value) {
            addCriterion("userKey =", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyNotEqualTo(String value) {
            addCriterion("userKey <>", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyGreaterThan(String value) {
            addCriterion("userKey >", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyGreaterThanOrEqualTo(String value) {
            addCriterion("userKey >=", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyLessThan(String value) {
            addCriterion("userKey <", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyLessThanOrEqualTo(String value) {
            addCriterion("userKey <=", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyLike(String value) {
            addCriterion("userKey like", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyNotLike(String value) {
            addCriterion("userKey not like", value, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyIn(List<String> values) {
            addCriterion("userKey in", values, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyNotIn(List<String> values) {
            addCriterion("userKey not in", values, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyBetween(String value1, String value2) {
            addCriterion("userKey between", value1, value2, "userkey");
            return (Criteria) this;
        }

        public Criteria andUserkeyNotBetween(String value1, String value2) {
            addCriterion("userKey not between", value1, value2, "userkey");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNull() {
            addCriterion("userType is null");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNotNull() {
            addCriterion("userType is not null");
            return (Criteria) this;
        }

        public Criteria andUsertypeEqualTo(Integer value) {
            addCriterion("userType =", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotEqualTo(Integer value) {
            addCriterion("userType <>", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThan(Integer value) {
            addCriterion("userType >", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("userType >=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThan(Integer value) {
            addCriterion("userType <", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThanOrEqualTo(Integer value) {
            addCriterion("userType <=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeIn(List<Integer> values) {
            addCriterion("userType in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotIn(List<Integer> values) {
            addCriterion("userType not in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeBetween(Integer value1, Integer value2) {
            addCriterion("userType between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("userType not between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUserlevelIsNull() {
            addCriterion("userLevel is null");
            return (Criteria) this;
        }

        public Criteria andUserlevelIsNotNull() {
            addCriterion("userLevel is not null");
            return (Criteria) this;
        }

        public Criteria andUserlevelEqualTo(Integer value) {
            addCriterion("userLevel =", value, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelNotEqualTo(Integer value) {
            addCriterion("userLevel <>", value, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelGreaterThan(Integer value) {
            addCriterion("userLevel >", value, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("userLevel >=", value, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelLessThan(Integer value) {
            addCriterion("userLevel <", value, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelLessThanOrEqualTo(Integer value) {
            addCriterion("userLevel <=", value, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelIn(List<Integer> values) {
            addCriterion("userLevel in", values, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelNotIn(List<Integer> values) {
            addCriterion("userLevel not in", values, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelBetween(Integer value1, Integer value2) {
            addCriterion("userLevel between", value1, value2, "userlevel");
            return (Criteria) this;
        }

        public Criteria andUserlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("userLevel not between", value1, value2, "userlevel");
            return (Criteria) this;
        }

        public Criteria andArealevel1IsNull() {
            addCriterion("areaLevel1 is null");
            return (Criteria) this;
        }

        public Criteria andArealevel1IsNotNull() {
            addCriterion("areaLevel1 is not null");
            return (Criteria) this;
        }

        public Criteria andArealevel1EqualTo(Integer value) {
            addCriterion("areaLevel1 =", value, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1NotEqualTo(Integer value) {
            addCriterion("areaLevel1 <>", value, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1GreaterThan(Integer value) {
            addCriterion("areaLevel1 >", value, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1GreaterThanOrEqualTo(Integer value) {
            addCriterion("areaLevel1 >=", value, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1LessThan(Integer value) {
            addCriterion("areaLevel1 <", value, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1LessThanOrEqualTo(Integer value) {
            addCriterion("areaLevel1 <=", value, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1In(List<Integer> values) {
            addCriterion("areaLevel1 in", values, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1NotIn(List<Integer> values) {
            addCriterion("areaLevel1 not in", values, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1Between(Integer value1, Integer value2) {
            addCriterion("areaLevel1 between", value1, value2, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel1NotBetween(Integer value1, Integer value2) {
            addCriterion("areaLevel1 not between", value1, value2, "arealevel1");
            return (Criteria) this;
        }

        public Criteria andArealevel2IsNull() {
            addCriterion("areaLevel2 is null");
            return (Criteria) this;
        }

        public Criteria andArealevel2IsNotNull() {
            addCriterion("areaLevel2 is not null");
            return (Criteria) this;
        }

        public Criteria andArealevel2EqualTo(Integer value) {
            addCriterion("areaLevel2 =", value, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2NotEqualTo(Integer value) {
            addCriterion("areaLevel2 <>", value, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2GreaterThan(Integer value) {
            addCriterion("areaLevel2 >", value, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2GreaterThanOrEqualTo(Integer value) {
            addCriterion("areaLevel2 >=", value, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2LessThan(Integer value) {
            addCriterion("areaLevel2 <", value, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2LessThanOrEqualTo(Integer value) {
            addCriterion("areaLevel2 <=", value, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2In(List<Integer> values) {
            addCriterion("areaLevel2 in", values, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2NotIn(List<Integer> values) {
            addCriterion("areaLevel2 not in", values, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2Between(Integer value1, Integer value2) {
            addCriterion("areaLevel2 between", value1, value2, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel2NotBetween(Integer value1, Integer value2) {
            addCriterion("areaLevel2 not between", value1, value2, "arealevel2");
            return (Criteria) this;
        }

        public Criteria andArealevel3IsNull() {
            addCriterion("areaLevel3 is null");
            return (Criteria) this;
        }

        public Criteria andArealevel3IsNotNull() {
            addCriterion("areaLevel3 is not null");
            return (Criteria) this;
        }

        public Criteria andArealevel3EqualTo(Integer value) {
            addCriterion("areaLevel3 =", value, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3NotEqualTo(Integer value) {
            addCriterion("areaLevel3 <>", value, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3GreaterThan(Integer value) {
            addCriterion("areaLevel3 >", value, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3GreaterThanOrEqualTo(Integer value) {
            addCriterion("areaLevel3 >=", value, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3LessThan(Integer value) {
            addCriterion("areaLevel3 <", value, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3LessThanOrEqualTo(Integer value) {
            addCriterion("areaLevel3 <=", value, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3In(List<Integer> values) {
            addCriterion("areaLevel3 in", values, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3NotIn(List<Integer> values) {
            addCriterion("areaLevel3 not in", values, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3Between(Integer value1, Integer value2) {
            addCriterion("areaLevel3 between", value1, value2, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andArealevel3NotBetween(Integer value1, Integer value2) {
            addCriterion("areaLevel3 not between", value1, value2, "arealevel3");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameIsNull() {
            addCriterion("enterpriseName is null");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameIsNotNull() {
            addCriterion("enterpriseName is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameEqualTo(String value) {
            addCriterion("enterpriseName =", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameNotEqualTo(String value) {
            addCriterion("enterpriseName <>", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameGreaterThan(String value) {
            addCriterion("enterpriseName >", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameGreaterThanOrEqualTo(String value) {
            addCriterion("enterpriseName >=", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameLessThan(String value) {
            addCriterion("enterpriseName <", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameLessThanOrEqualTo(String value) {
            addCriterion("enterpriseName <=", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameLike(String value) {
            addCriterion("enterpriseName like", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameNotLike(String value) {
            addCriterion("enterpriseName not like", value, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameIn(List<String> values) {
            addCriterion("enterpriseName in", values, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameNotIn(List<String> values) {
            addCriterion("enterpriseName not in", values, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameBetween(String value1, String value2) {
            addCriterion("enterpriseName between", value1, value2, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andEnterprisenameNotBetween(String value1, String value2) {
            addCriterion("enterpriseName not between", value1, value2, "enterprisename");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeIsNull() {
            addCriterion("organizationCode is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeIsNotNull() {
            addCriterion("organizationCode is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeEqualTo(String value) {
            addCriterion("organizationCode =", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotEqualTo(String value) {
            addCriterion("organizationCode <>", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeGreaterThan(String value) {
            addCriterion("organizationCode >", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeGreaterThanOrEqualTo(String value) {
            addCriterion("organizationCode >=", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeLessThan(String value) {
            addCriterion("organizationCode <", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeLessThanOrEqualTo(String value) {
            addCriterion("organizationCode <=", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeLike(String value) {
            addCriterion("organizationCode like", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotLike(String value) {
            addCriterion("organizationCode not like", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeIn(List<String> values) {
            addCriterion("organizationCode in", values, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotIn(List<String> values) {
            addCriterion("organizationCode not in", values, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeBetween(String value1, String value2) {
            addCriterion("organizationCode between", value1, value2, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotBetween(String value1, String value2) {
            addCriterion("organizationCode not between", value1, value2, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andContactsIsNull() {
            addCriterion("contacts is null");
            return (Criteria) this;
        }

        public Criteria andContactsIsNotNull() {
            addCriterion("contacts is not null");
            return (Criteria) this;
        }

        public Criteria andContactsEqualTo(String value) {
            addCriterion("contacts =", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotEqualTo(String value) {
            addCriterion("contacts <>", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsGreaterThan(String value) {
            addCriterion("contacts >", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsGreaterThanOrEqualTo(String value) {
            addCriterion("contacts >=", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsLessThan(String value) {
            addCriterion("contacts <", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsLessThanOrEqualTo(String value) {
            addCriterion("contacts <=", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsLike(String value) {
            addCriterion("contacts like", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotLike(String value) {
            addCriterion("contacts not like", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsIn(List<String> values) {
            addCriterion("contacts in", values, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotIn(List<String> values) {
            addCriterion("contacts not in", values, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsBetween(String value1, String value2) {
            addCriterion("contacts between", value1, value2, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotBetween(String value1, String value2) {
            addCriterion("contacts not between", value1, value2, "contacts");
            return (Criteria) this;
        }

        public Criteria andSitenameIsNull() {
            addCriterion("siteName is null");
            return (Criteria) this;
        }

        public Criteria andSitenameIsNotNull() {
            addCriterion("siteName is not null");
            return (Criteria) this;
        }

        public Criteria andSitenameEqualTo(String value) {
            addCriterion("siteName =", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameNotEqualTo(String value) {
            addCriterion("siteName <>", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameGreaterThan(String value) {
            addCriterion("siteName >", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameGreaterThanOrEqualTo(String value) {
            addCriterion("siteName >=", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameLessThan(String value) {
            addCriterion("siteName <", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameLessThanOrEqualTo(String value) {
            addCriterion("siteName <=", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameLike(String value) {
            addCriterion("siteName like", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameNotLike(String value) {
            addCriterion("siteName not like", value, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameIn(List<String> values) {
            addCriterion("siteName in", values, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameNotIn(List<String> values) {
            addCriterion("siteName not in", values, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameBetween(String value1, String value2) {
            addCriterion("siteName between", value1, value2, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitenameNotBetween(String value1, String value2) {
            addCriterion("siteName not between", value1, value2, "sitename");
            return (Criteria) this;
        }

        public Criteria andSitetypeIsNull() {
            addCriterion("siteType is null");
            return (Criteria) this;
        }

        public Criteria andSitetypeIsNotNull() {
            addCriterion("siteType is not null");
            return (Criteria) this;
        }

        public Criteria andSitetypeEqualTo(Integer value) {
            addCriterion("siteType =", value, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeNotEqualTo(Integer value) {
            addCriterion("siteType <>", value, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeGreaterThan(Integer value) {
            addCriterion("siteType >", value, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("siteType >=", value, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeLessThan(Integer value) {
            addCriterion("siteType <", value, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeLessThanOrEqualTo(Integer value) {
            addCriterion("siteType <=", value, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeIn(List<Integer> values) {
            addCriterion("siteType in", values, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeNotIn(List<Integer> values) {
            addCriterion("siteType not in", values, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeBetween(Integer value1, Integer value2) {
            addCriterion("siteType between", value1, value2, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("siteType not between", value1, value2, "sitetype");
            return (Criteria) this;
        }

        public Criteria andSitedomainIsNull() {
            addCriterion("siteDomain is null");
            return (Criteria) this;
        }

        public Criteria andSitedomainIsNotNull() {
            addCriterion("siteDomain is not null");
            return (Criteria) this;
        }

        public Criteria andSitedomainEqualTo(String value) {
            addCriterion("siteDomain =", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainNotEqualTo(String value) {
            addCriterion("siteDomain <>", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainGreaterThan(String value) {
            addCriterion("siteDomain >", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainGreaterThanOrEqualTo(String value) {
            addCriterion("siteDomain >=", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainLessThan(String value) {
            addCriterion("siteDomain <", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainLessThanOrEqualTo(String value) {
            addCriterion("siteDomain <=", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainLike(String value) {
            addCriterion("siteDomain like", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainNotLike(String value) {
            addCriterion("siteDomain not like", value, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainIn(List<String> values) {
            addCriterion("siteDomain in", values, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainNotIn(List<String> values) {
            addCriterion("siteDomain not in", values, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainBetween(String value1, String value2) {
            addCriterion("siteDomain between", value1, value2, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andSitedomainNotBetween(String value1, String value2) {
            addCriterion("siteDomain not between", value1, value2, "sitedomain");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseIsNull() {
            addCriterion("businessLicense is null");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseIsNotNull() {
            addCriterion("businessLicense is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseEqualTo(String value) {
            addCriterion("businessLicense =", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseNotEqualTo(String value) {
            addCriterion("businessLicense <>", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseGreaterThan(String value) {
            addCriterion("businessLicense >", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseGreaterThanOrEqualTo(String value) {
            addCriterion("businessLicense >=", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseLessThan(String value) {
            addCriterion("businessLicense <", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseLessThanOrEqualTo(String value) {
            addCriterion("businessLicense <=", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseLike(String value) {
            addCriterion("businessLicense like", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseNotLike(String value) {
            addCriterion("businessLicense not like", value, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseIn(List<String> values) {
            addCriterion("businessLicense in", values, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseNotIn(List<String> values) {
            addCriterion("businessLicense not in", values, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseBetween(String value1, String value2) {
            addCriterion("businessLicense between", value1, value2, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseNotBetween(String value1, String value2) {
            addCriterion("businessLicense not between", value1, value2, "businesslicense");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumIsNull() {
            addCriterion("businessLicenseRegisterNum is null");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumIsNotNull() {
            addCriterion("businessLicenseRegisterNum is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumEqualTo(String value) {
            addCriterion("businessLicenseRegisterNum =", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumNotEqualTo(String value) {
            addCriterion("businessLicenseRegisterNum <>", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumGreaterThan(String value) {
            addCriterion("businessLicenseRegisterNum >", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumGreaterThanOrEqualTo(String value) {
            addCriterion("businessLicenseRegisterNum >=", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumLessThan(String value) {
            addCriterion("businessLicenseRegisterNum <", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumLessThanOrEqualTo(String value) {
            addCriterion("businessLicenseRegisterNum <=", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumLike(String value) {
            addCriterion("businessLicenseRegisterNum like", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumNotLike(String value) {
            addCriterion("businessLicenseRegisterNum not like", value, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumIn(List<String> values) {
            addCriterion("businessLicenseRegisterNum in", values, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumNotIn(List<String> values) {
            addCriterion("businessLicenseRegisterNum not in", values, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumBetween(String value1, String value2) {
            addCriterion("businessLicenseRegisterNum between", value1, value2, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andBusinesslicenseregisternumNotBetween(String value1, String value2) {
            addCriterion("businessLicenseRegisterNum not between", value1, value2, "businesslicenseregisternum");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNull() {
            addCriterion("createdTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNotNull() {
            addCriterion("createdTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeEqualTo(Date value) {
            addCriterion("createdTime =", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotEqualTo(Date value) {
            addCriterion("createdTime <>", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThan(Date value) {
            addCriterion("createdTime >", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createdTime >=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThan(Date value) {
            addCriterion("createdTime <", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThanOrEqualTo(Date value) {
            addCriterion("createdTime <=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIn(List<Date> values) {
            addCriterion("createdTime in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotIn(List<Date> values) {
            addCriterion("createdTime not in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeBetween(Date value1, Date value2) {
            addCriterion("createdTime between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotBetween(Date value1, Date value2) {
            addCriterion("createdTime not between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreateduserIsNull() {
            addCriterion("createdUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateduserIsNotNull() {
            addCriterion("createdUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateduserEqualTo(String value) {
            addCriterion("createdUser =", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotEqualTo(String value) {
            addCriterion("createdUser <>", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserGreaterThan(String value) {
            addCriterion("createdUser >", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserGreaterThanOrEqualTo(String value) {
            addCriterion("createdUser >=", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserLessThan(String value) {
            addCriterion("createdUser <", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserLessThanOrEqualTo(String value) {
            addCriterion("createdUser <=", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserLike(String value) {
            addCriterion("createdUser like", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotLike(String value) {
            addCriterion("createdUser not like", value, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserIn(List<String> values) {
            addCriterion("createdUser in", values, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotIn(List<String> values) {
            addCriterion("createdUser not in", values, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserBetween(String value1, String value2) {
            addCriterion("createdUser between", value1, value2, "createduser");
            return (Criteria) this;
        }

        public Criteria andCreateduserNotBetween(String value1, String value2) {
            addCriterion("createdUser not between", value1, value2, "createduser");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNull() {
            addCriterion("lastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNotNull() {
            addCriterion("lastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeEqualTo(Date value) {
            addCriterion("lastUpdateTime =", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotEqualTo(Date value) {
            addCriterion("lastUpdateTime <>", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThan(Date value) {
            addCriterion("lastUpdateTime >", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime >=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThan(Date value) {
            addCriterion("lastUpdateTime <", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime <=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIn(List<Date> values) {
            addCriterion("lastUpdateTime in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotIn(List<Date> values) {
            addCriterion("lastUpdateTime not in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime not between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserIsNull() {
            addCriterion("lastUpdateUser is null");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserIsNotNull() {
            addCriterion("lastUpdateUser is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserEqualTo(String value) {
            addCriterion("lastUpdateUser =", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserNotEqualTo(String value) {
            addCriterion("lastUpdateUser <>", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserGreaterThan(String value) {
            addCriterion("lastUpdateUser >", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("lastUpdateUser >=", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserLessThan(String value) {
            addCriterion("lastUpdateUser <", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserLessThanOrEqualTo(String value) {
            addCriterion("lastUpdateUser <=", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserLike(String value) {
            addCriterion("lastUpdateUser like", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserNotLike(String value) {
            addCriterion("lastUpdateUser not like", value, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserIn(List<String> values) {
            addCriterion("lastUpdateUser in", values, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserNotIn(List<String> values) {
            addCriterion("lastUpdateUser not in", values, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserBetween(String value1, String value2) {
            addCriterion("lastUpdateUser between", value1, value2, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andLastupdateuserNotBetween(String value1, String value2) {
            addCriterion("lastUpdateUser not between", value1, value2, "lastupdateuser");
            return (Criteria) this;
        }

        public Criteria andReasonidIsNull() {
            addCriterion("reasonId is null");
            return (Criteria) this;
        }

        public Criteria andReasonidIsNotNull() {
            addCriterion("reasonId is not null");
            return (Criteria) this;
        }

        public Criteria andReasonidEqualTo(Integer value) {
            addCriterion("reasonId =", value, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidNotEqualTo(Integer value) {
            addCriterion("reasonId <>", value, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidGreaterThan(Integer value) {
            addCriterion("reasonId >", value, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidGreaterThanOrEqualTo(Integer value) {
            addCriterion("reasonId >=", value, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidLessThan(Integer value) {
            addCriterion("reasonId <", value, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidLessThanOrEqualTo(Integer value) {
            addCriterion("reasonId <=", value, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidIn(List<Integer> values) {
            addCriterion("reasonId in", values, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidNotIn(List<Integer> values) {
            addCriterion("reasonId not in", values, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidBetween(Integer value1, Integer value2) {
            addCriterion("reasonId between", value1, value2, "reasonid");
            return (Criteria) this;
        }

        public Criteria andReasonidNotBetween(Integer value1, Integer value2) {
            addCriterion("reasonId not between", value1, value2, "reasonid");
            return (Criteria) this;
        }

        public Criteria andIsoldIsNull() {
            addCriterion("isOld is null");
            return (Criteria) this;
        }

        public Criteria andIsoldIsNotNull() {
            addCriterion("isOld is not null");
            return (Criteria) this;
        }

        public Criteria andIsoldEqualTo(Integer value) {
            addCriterion("isOld =", value, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldNotEqualTo(Integer value) {
            addCriterion("isOld <>", value, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldGreaterThan(Integer value) {
            addCriterion("isOld >", value, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldGreaterThanOrEqualTo(Integer value) {
            addCriterion("isOld >=", value, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldLessThan(Integer value) {
            addCriterion("isOld <", value, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldLessThanOrEqualTo(Integer value) {
            addCriterion("isOld <=", value, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldIn(List<Integer> values) {
            addCriterion("isOld in", values, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldNotIn(List<Integer> values) {
            addCriterion("isOld not in", values, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldBetween(Integer value1, Integer value2) {
            addCriterion("isOld between", value1, value2, "isold");
            return (Criteria) this;
        }

        public Criteria andIsoldNotBetween(Integer value1, Integer value2) {
            addCriterion("isOld not between", value1, value2, "isold");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("reason not between", value1, value2, "reason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_user_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 13 18:33:37 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_user_info
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}