package com.letvcloud.uc.ms.model;

import java.io.Serializable;
import java.util.Date;

public class UcCountry implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_country.id
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_country.countryName
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    private String countryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_country.countryDomainName
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    private String countrydomainname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_country.countryAreaNum
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    private String countryareanum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_country.createdTime
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_country.lastUpdateTime
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    private Date lastupdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_country.id
     *
     * @return the value of uc_country.id
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_country.id
     *
     * @param id the value for uc_country.id
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_country.countryName
     *
     * @return the value of uc_country.countryName
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_country.countryName
     *
     * @param countryname the value for uc_country.countryName
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname == null ? null : countryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_country.countryDomainName
     *
     * @return the value of uc_country.countryDomainName
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public String getCountrydomainname() {
        return countrydomainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_country.countryDomainName
     *
     * @param countrydomainname the value for uc_country.countryDomainName
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public void setCountrydomainname(String countrydomainname) {
        this.countrydomainname = countrydomainname == null ? null : countrydomainname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_country.countryAreaNum
     *
     * @return the value of uc_country.countryAreaNum
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public String getCountryareanum() {
        return countryareanum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_country.countryAreaNum
     *
     * @param countryareanum the value for uc_country.countryAreaNum
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public void setCountryareanum(String countryareanum) {
        this.countryareanum = countryareanum == null ? null : countryareanum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_country.createdTime
     *
     * @return the value of uc_country.createdTime
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_country.createdTime
     *
     * @param createdtime the value for uc_country.createdTime
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_country.lastUpdateTime
     *
     * @return the value of uc_country.lastUpdateTime
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_country.lastUpdateTime
     *
     * @param lastupdatetime the value for uc_country.lastUpdateTime
     *
     * @mbggenerated Thu Aug 27 16:59:46 CST 2015
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }
}