package com.letvcloud.uc.ms.model;

import java.io.Serializable;
import java.util.Date;

public class UcUserInfo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.id
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.parentId
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.emailStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Byte emailstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.userStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Byte userstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.userUnique
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String userunique;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.examineStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Byte examinestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.userAvatar
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String useravatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.idCard
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.idCardPhoto
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String idcardphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.email
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.password
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.mobile
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.userKey
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.userType
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.userLevel
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer userlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.areaLevel1
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer arealevel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.areaLevel2
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer arealevel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.areaLevel3
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer arealevel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.address
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.enterpriseName
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String enterprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.organizationCode
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String organizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.contacts
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.siteName
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String sitename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.siteType
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer sitetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.siteDomain
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String sitedomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.businessLicense
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String businesslicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.businessLicenseRegisterNum
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String businesslicenseregisternum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.createdTime
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.createdUser
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String createduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.lastUpdateTime
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.lastUpdateUser
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.reasonId
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer reasonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.isOld
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    private Integer isold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.reason
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    
    private String reason;
    
    private UcCountry ucCountry;
    
    public UcCountry getUcCountry() {
    
        return ucCountry;
    }
    
    public void setUcCountry(UcCountry ucCountry) {
    
        this.ucCountry = ucCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.id
     *
     * @return the value of uc_user_info.id
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.id
     *
     * @param id the value for uc_user_info.id
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.parentId
     *
     * @return the value of uc_user_info.parentId
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.parentId
     *
     * @param parentid the value for uc_user_info.parentId
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.emailStatus
     *
     * @return the value of uc_user_info.emailStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Byte getEmailstatus() {
        return emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.emailStatus
     *
     * @param emailstatus the value for uc_user_info.emailStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setEmailstatus(Byte emailstatus) {
        this.emailstatus = emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.userStatus
     *
     * @return the value of uc_user_info.userStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Byte getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.userStatus
     *
     * @param userstatus the value for uc_user_info.userStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setUserstatus(Byte userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.userUnique
     *
     * @return the value of uc_user_info.userUnique
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getUserunique() {
        return userunique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.userUnique
     *
     * @param userunique the value for uc_user_info.userUnique
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setUserunique(String userunique) {
        this.userunique = userunique == null ? null : userunique.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.examineStatus
     *
     * @return the value of uc_user_info.examineStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Byte getExaminestatus() {
        return examinestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.examineStatus
     *
     * @param examinestatus the value for uc_user_info.examineStatus
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setExaminestatus(Byte examinestatus) {
        this.examinestatus = examinestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.userAvatar
     *
     * @return the value of uc_user_info.userAvatar
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getUseravatar() {
        return useravatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.userAvatar
     *
     * @param useravatar the value for uc_user_info.userAvatar
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setUseravatar(String useravatar) {
        this.useravatar = useravatar == null ? null : useravatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.idCard
     *
     * @return the value of uc_user_info.idCard
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.idCard
     *
     * @param idcard the value for uc_user_info.idCard
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.idCardPhoto
     *
     * @return the value of uc_user_info.idCardPhoto
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getIdcardphoto() {
        return idcardphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.idCardPhoto
     *
     * @param idcardphoto the value for uc_user_info.idCardPhoto
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setIdcardphoto(String idcardphoto) {
        this.idcardphoto = idcardphoto == null ? null : idcardphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.email
     *
     * @return the value of uc_user_info.email
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.email
     *
     * @param email the value for uc_user_info.email
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.password
     *
     * @return the value of uc_user_info.password
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.password
     *
     * @param password the value for uc_user_info.password
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.mobile
     *
     * @return the value of uc_user_info.mobile
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.mobile
     *
     * @param mobile the value for uc_user_info.mobile
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.userKey
     *
     * @return the value of uc_user_info.userKey
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.userKey
     *
     * @param userkey the value for uc_user_info.userKey
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey == null ? null : userkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.userType
     *
     * @return the value of uc_user_info.userType
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.userType
     *
     * @param usertype the value for uc_user_info.userType
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.userLevel
     *
     * @return the value of uc_user_info.userLevel
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getUserlevel() {
        return userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.userLevel
     *
     * @param userlevel the value for uc_user_info.userLevel
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setUserlevel(Integer userlevel) {
        this.userlevel = userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.areaLevel1
     *
     * @return the value of uc_user_info.areaLevel1
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getArealevel1() {
        return arealevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.areaLevel1
     *
     * @param arealevel1 the value for uc_user_info.areaLevel1
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setArealevel1(Integer arealevel1) {
        this.arealevel1 = arealevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.areaLevel2
     *
     * @return the value of uc_user_info.areaLevel2
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getArealevel2() {
        return arealevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.areaLevel2
     *
     * @param arealevel2 the value for uc_user_info.areaLevel2
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setArealevel2(Integer arealevel2) {
        this.arealevel2 = arealevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.areaLevel3
     *
     * @return the value of uc_user_info.areaLevel3
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getArealevel3() {
        return arealevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.areaLevel3
     *
     * @param arealevel3 the value for uc_user_info.areaLevel3
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setArealevel3(Integer arealevel3) {
        this.arealevel3 = arealevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.address
     *
     * @return the value of uc_user_info.address
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.address
     *
     * @param address the value for uc_user_info.address
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.enterpriseName
     *
     * @return the value of uc_user_info.enterpriseName
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.enterpriseName
     *
     * @param enterprisename the value for uc_user_info.enterpriseName
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename == null ? null : enterprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.organizationCode
     *
     * @return the value of uc_user_info.organizationCode
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getOrganizationcode() {
        return organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.organizationCode
     *
     * @param organizationcode the value for uc_user_info.organizationCode
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setOrganizationcode(String organizationcode) {
        this.organizationcode = organizationcode == null ? null : organizationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.contacts
     *
     * @return the value of uc_user_info.contacts
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.contacts
     *
     * @param contacts the value for uc_user_info.contacts
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.siteName
     *
     * @return the value of uc_user_info.siteName
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.siteName
     *
     * @param sitename the value for uc_user_info.siteName
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setSitename(String sitename) {
        this.sitename = sitename == null ? null : sitename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.siteType
     *
     * @return the value of uc_user_info.siteType
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getSitetype() {
        return sitetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.siteType
     *
     * @param sitetype the value for uc_user_info.siteType
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setSitetype(Integer sitetype) {
        this.sitetype = sitetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.siteDomain
     *
     * @return the value of uc_user_info.siteDomain
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getSitedomain() {
        return sitedomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.siteDomain
     *
     * @param sitedomain the value for uc_user_info.siteDomain
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setSitedomain(String sitedomain) {
        this.sitedomain = sitedomain == null ? null : sitedomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.businessLicense
     *
     * @return the value of uc_user_info.businessLicense
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getBusinesslicense() {
        return businesslicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.businessLicense
     *
     * @param businesslicense the value for uc_user_info.businessLicense
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setBusinesslicense(String businesslicense) {
        this.businesslicense = businesslicense == null ? null : businesslicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.businessLicenseRegisterNum
     *
     * @return the value of uc_user_info.businessLicenseRegisterNum
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getBusinesslicenseregisternum() {
        return businesslicenseregisternum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.businessLicenseRegisterNum
     *
     * @param businesslicenseregisternum the value for uc_user_info.businessLicenseRegisterNum
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setBusinesslicenseregisternum(String businesslicenseregisternum) {
        this.businesslicenseregisternum = businesslicenseregisternum == null ? null : businesslicenseregisternum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.createdTime
     *
     * @return the value of uc_user_info.createdTime
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.createdTime
     *
     * @param createdtime the value for uc_user_info.createdTime
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.createdUser
     *
     * @return the value of uc_user_info.createdUser
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getCreateduser() {
        return createduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.createdUser
     *
     * @param createduser the value for uc_user_info.createdUser
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setCreateduser(String createduser) {
        this.createduser = createduser == null ? null : createduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.lastUpdateTime
     *
     * @return the value of uc_user_info.lastUpdateTime
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.lastUpdateTime
     *
     * @param lastupdatetime the value for uc_user_info.lastUpdateTime
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.lastUpdateUser
     *
     * @return the value of uc_user_info.lastUpdateUser
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.lastUpdateUser
     *
     * @param lastupdateuser the value for uc_user_info.lastUpdateUser
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.reasonId
     *
     * @return the value of uc_user_info.reasonId
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getReasonid() {
        return reasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.reasonId
     *
     * @param reasonid the value for uc_user_info.reasonId
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setReasonid(Integer reasonid) {
        this.reasonid = reasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.isOld
     *
     * @return the value of uc_user_info.isOld
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public Integer getIsold() {
        return isold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.isOld
     *
     * @param isold the value for uc_user_info.isOld
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setIsold(Integer isold) {
        this.isold = isold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.reason
     *
     * @return the value of uc_user_info.reason
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.reason
     *
     * @param reason the value for uc_user_info.reason
     *
     * @mbggenerated Thu Aug 13 18:33:37 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}